AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FargateCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MyFargateCluster

  FargateTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: MyFargateTask
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: arn:aws:iam::012683545385:role/ecsTaskExecutionRole
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: MyContainer
          Image: public.ecr.aws/s9u2t8a1/ecr-bamboo:latest
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp

  FargateService:
    Type: AWS::ECS::Service
    DependsOn: FargateTaskDefinition
    Properties:
      Cluster: !Ref FargateCluster
      ServiceName: MyFargateService
      TaskDefinition: !Ref FargateTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-08ba288b6b6e988df
            - subnet-0d23a674d87322c3c
          SecurityGroups:
            - sg-09337b45d56c1335d
          AssignPublicIp: ENABLED
