AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: my-pipeline-cf
      RoleArn: arn:aws:iam::012683545385:role/my-pipeline-role
      ArtifactStore:
        Type: S3
        Location: my-pipeline-bucket-cf
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: S3
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                S3Bucket: my-pipeline-s3
                S3ObjectKey: package.zip
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ProjectName: my-codebuild-project
              RunOrder: 2

        # - Name: Deploy
        #   Actions:
        #     - Name: DeployAction
        #       ActionTypeId:
        #         Category: Deploy
        #         Owner: AWS
        #         Version: "1"
        #         Provider: CodeDeployToECS
        #       InputArtifacts:
        #         - Name: SourceArtifact
        #       Configuration:
        #         ApplicationName: rp-application
        #         DeploymentGroupName: rp-deploy-group
        #         TaskDefinitionTemplateArtifact: SourceArtifact
        #         EcsClusterName: MyFargateCluster
        #         TaskCount: 1
        #       RunOrder: 3
